version: '3.9'

services:
  web:
    build: ./app
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - ./auto_business_project/:/home/vsevolod/PythonProjects/auto_business_project
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev