# Generated by Django 3.2.7 on 2021-10-01 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_business', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyers',
            old_name='date_created_in_db',
            new_name='added_date',
        ),
        migrations.RenameField(
            model_name='buyersorder',
            old_name='date_created_in_db',
            new_name='added_date',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='date_created_in_db',
            new_name='added_date',
        ),
        migrations.RenameField(
            model_name='discountshowrooms',
            old_name='date_created_in_db',
            new_name='added_date',
        ),
        migrations.RenameField(
            model_name='discountsuppliers',
            old_name='date_created_in_db',
            new_name='added_date',
        ),
        migrations.RenameField(
            model_name='salesshowroomsbuyers',
            old_name='date_created_in_db',
            new_name='added_date',
        ),
        migrations.RenameField(
            model_name='salessuppliersshowrooms',
            old_name='date_created_in_db',
            new_name='added_date',
        ),
        migrations.RenameField(
            model_name='showrooms',
            old_name='date_created_in_db',
            new_name='added_date',
        ),
        migrations.RenameField(
            model_name='suppliers',
            old_name='date_created_in_db',
            new_name='added_date',
        ),
        migrations.AddField(
            model_name='buyersorder',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='color',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyers',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='buyers',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='buyersorder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='cars',
            name='engine',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.6), django.core.validators.MaxValueValidator(9.0)]),
        ),
        migrations.AlterField(
            model_name='cars',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='salesshowroomsbuyers',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='salessuppliersshowrooms',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='showrooms',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='showroomscarsforsale',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='number_of_buyers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplierscarsforsale',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
