# Generated by Django 3.2.7 on 2021-10-01 15:24

import core.filters_models_field.decimal_range_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_business', '0003_alter_cars_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='balance',
            field=core.filters_models_field.decimal_range_field.DecimalRangeField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='buyersorder',
            name='price',
            field=core.filters_models_field.decimal_range_field.DecimalRangeField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='salesshowroomsbuyers',
            name='price',
            field=core.filters_models_field.decimal_range_field.DecimalRangeField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='salessuppliersshowrooms',
            name='price',
            field=core.filters_models_field.decimal_range_field.DecimalRangeField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='showrooms',
            name='balance',
            field=core.filters_models_field.decimal_range_field.DecimalRangeField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='showroomscarsforsale',
            name='price',
            field=core.filters_models_field.decimal_range_field.DecimalRangeField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='balance',
            field=core.filters_models_field.decimal_range_field.DecimalRangeField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='supplierscarsforsale',
            name='price',
            field=core.filters_models_field.decimal_range_field.DecimalRangeField(decimal_places=2, max_digits=20),
        ),
    ]
