# Generated by Django 3.2.7 on 2021-10-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_business', '0005_auto_20211001_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image_url',
            field=models.URLField(max_length=300),
        ),
    ]
