# Generated by Django 3.2.7 on 2021-10-06 12:16

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auto_business', '0006_alter_cars_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='country',
            field=django_countries.fields.CountryField(max_length=746, multiple=True),
        ),
        migrations.AlterField(
            model_name='buyers',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
